MusicTaggerFCN:

  hyperparameters:
    # Parameters for training
    num_epochs: 20
    batch_size: 128
    learning_rate: 0.0003    
    patience: 3
    refinement: 2
    refinement_lr_factor: 0.1
    
  audio:
    # The model architecture is designed for these settings              
    sample_rate: 12000
    fft_frame_size: 512
    hop_size: 256
    num_mel_bands: 96    